name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create environment file
      run: |
        cat > env.js << EOF
        window.ENV = {
          API_BASE_URL: '${{ secrets.API_BASE_URL }}',
          API_KEY: '${{ secrets.API_KEY }}',
          BACKUP_URL: '${{ secrets.BACKUP_URL }}'
        };
        EOF
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
